### ISSUE TITLE
How to Consume Messages Stored in S3 Minio Storage?

### ISSUE THREAD

**Issue by tqanh2609** [Aiven-Open/tiered-storage-for-apache-kafka#635]
# What can we help you with?

I’m new to the tiered storage function and am currently building/testing it. I have successfully built Aiven's plugins with my Kraft-mode Kafka cluster. On the producer side, everything works just fine—the messages flow to the enabled remote storage topic, and the files are then moved to Minio for storage. At this point, there are still about 100k messages left in the brokers.

I then tried to start a consumer, which in my case includes an Iceberg Sink Kafka Connector [(https://github.com/databricks/iceberg-kafka-connect)](https://github.com/Aiven-Open/tiered-storage-for-apache-kafka/issues/url) and a Python application as the consumer.

My expectation was that when any consumer starts consuming a topic with the remote storage function enabled for the first time, all the logs stored in Minio would be loaded into the cache folder, and then the consumer would process both the messages currently on the local disk and those loaded into the cache folder.

However, in my experience, the consumer only consumes the messages in the local disk (the 100k). When I checked the broker's container, I observed that the cache folder was being loaded with the log files that have the same names as those in Minio, but the consumer does not consume them.

After checking the logs of both the brokers and the Kafka connector, I found no errors.

# Where would you expect to find this information?

It would be greatly appreciated if there are tutorials or documentation on how to consume messages (via Kafka Connect, Python/PySpark, Apache Pinot, etc.) from a topic with remote storage enabled!

**Comment by jeqo** [comment]
Hi @tqanh2609! Thanks for reaching out and flagging this issue. 

Could you confirm what version of Kafka are you using, and share the tiered-storage related configurations used?

It would also be useful to confirm if you have the same issue with the demos: https://github.com/Aiven-Open/tiered-storage-for-apache-kafka/blob/main/demo/README.md#minio-s3-as-remote-storage-compose-s3-minioyml: it uses minio and has disk cache setup. 

I quickly tested it and it consumes from remote storage as expected. We should add a demo with KRaft though https://github.com/Aiven-Open/tiered-storage-for-apache-kafka/issues/641

In general there is nothing "special" with tiered-storage on how to produce/consume, it should be transparent. For instance, from the console consumer:

```
kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic topic1 --from-beginning --max-messages 10 \
--property print.offset=true \
--property print.partition=true
Partition:0     Offset:0 ...
```

Looking forward to your feedback

**Comment by tqanh2609** [comment]
Hi @jeqo,
Thank you for taking the time to reply to me.
I tested using the demos: https://github.com/Aiven-Open/tiered-storage-for-apache-kafka/blob/main/demo/README.md#minio-s3-as-remote-storage-compose-s3-minioyml, and everything worked flawlessly. Even the Kafbat Kafka UI (formerly known as provectuslabs/kafka-ui) can display the correct total number of messages (600k), instead of only the 100k remaining in the brokers as I mentioned before.
Based on this, I assume that the problems I was experiencing were due to the way I built my image and configured the KRaft-mode cluster.
Here is the Dockerfile I used to build the custom image:
```
FROM bitnami/kafka:3.9.0

USER root
 
RUN mkdir -p /opt/bitnami/kafka/plugins \
    &&  mkdir -p /opt/bitnami/kafka/tiered-storage-cache

RUN curl -L https://github.com/Aiven-Open/tiered-storage-for-apache-kafka/releases/download/2024-10-23-1729694047/core-0.0.1-SNAPSHOT.tgz -o /opt/bitnami/kafka/plugins/core.tgz \
    && curl -L https://github.com/Aiven-Open/tiered-storage-for-apache-kafka/releases/download/2024-10-23-1729694047/s3-0.0.1-SNAPSHOT.tgz -o /opt/bitnami/kafka/plugins/s3.tgz

RUN tar -xzf /opt/bitnami/kafka/plugins/core.tgz -C /opt/bitnami/kafka/plugins/ \
    && rm /opt/bitnami/kafka/plugins/core.tgz \
    && tar -xzf /opt/bitnami/kafka/plugins/s3.tgz -C /opt/bitnami/kafka/plugins/ \
    && rm /opt/bitnami/kafka/plugins/s3.tgz

RUN chown -R root:root /opt/bitnami/kafka \
    && chmod -R 777 /opt/bitnami/kafka/plugins /opt/bitnami/kafka/tiered-storage-cache
# Ensure that the subfolders in tiered-storage-cache will inherit the permissions
RUN chmod g+s /opt/bitnami/kafka/tiered-storage-cache

```
And here is my Docker Compose file for my KRaft-mode cluster:

```
version: '3.8'

x-controller-common: &controller-common
  image: tqanh/custom_image:3.9.0
  environment: &controller-env
    KAFKA_CFG_PROCESS_ROLES: "controller"
    KAFKA_KRAFT_CLUSTER_ID: "YFBtZwBcR6iE35DdIJAx6w"
    KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@controller-1:29092,2@controller-2:29093,3@controller-3:29094"
    KAFKA_CFG_SUPER_USERS: "User:sa"
    KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
    KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:SASL_PLAINTEXT"
    KAFKA_CFG_SASL_ENABLED_MECHANISMS: "PLAIN"
    KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL: "PLAIN"
    # KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL: "PLAIN"
    KAFKA_CONTROLLER_USER: "sa"
    KAFKA_CONTROLLER_PASSWORD: "000000"
    KAFKA_CFG_REMOTE_LOG_STORAGE_SYSTEM_ENABLE: "true"
    BITNAMI_DEBUG: "true"

x-broker-common: &broker-common
  image: tqanh/custom_image:3.9.0
  environment: &broker-env
    # ----- Common kafka broker config -----
    KAFKA_CFG_PROCESS_ROLES: "broker"
    KAFKA_CFG_SUPER_USERS: "User:sa"
    KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
    KAFKA_CFG_DELETE_TOPIC_ENABLE: "true"
    KAFKA_CFG_NUM_PARTITIONS: 12
    KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
    KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: 3
    KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 2
    KAFKA_CFG_MIN_INSYNC_REPLICAS: 2
    KAFKA_CFG_LOG_RETENTION_HOURS: 72 # The number of hours to keep a log file before deleting it (72 hours = 3 days)
    KAFKA_CFG_LOG_RETENTION_BYTES: 524288000 # Retain up to 500 MiB per partition of a topic before delete older segments
    KAFKA_CFG_LOG_SEGMENT_BYTES: 1073741824 # Log segment size of 1GB
    KAFKA_CFG_LOG_CLEANUP_POLICY: "delete"
    KAFKA_CFG_SOCKET_SEND_BUFFER_BYTES: 204800
    KAFKA_CFG_SOCKET_RECEIVE_BUFFER_BYTES: 204800
    KAFKA_HEAP_OPTS: "-Xmx1024m -Xms1024m"
    BITNAMI_DEBUG: "true" # Optional
    # KAFKA_CFG_CONNECTION_FAILED_AUTHENTICATION_DELAY_MS: 500
    # ----- Kafka LISTENERS config -----
    KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "BROKER"
    KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "BROKER:PLAINTEXT,EXTERNAL:SASL_PLAINTEXT,CONTROLLER:SASL_PLAINTEXT"
    ## KAFKA CONTROLLER
    KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
    KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@controller-1:29092,2@controller-2:29093,3@controller-3:29094"
    # ----- SASL_PLAINTEXT config -----
    KAFKA_CFG_SASL_ENABLED_MECHANISMS: "PLAIN"
    # KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL: "PLAIN"
    KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL: "PLAIN"
    # KAFKA_INTER_BROKER_USER: "sa"
    # KAFKA_INTER_BROKER_PASSWORD: "000000"
    KAFKA_CONTROLLER_USER: "sa"
    KAFKA_CONTROLLER_PASSWORD: "000000"
    ## CLIENT SETTINGS
    KAFKA_CLIENT_LISTENER_NAME: "EXTERNAL"
    KAFKA_CLIENT_USERS: "sa,da,va"
    KAFKA_CLIENT_PASSWORDS: "000000,111111,222222"
    # ----- Mount for prometheus/grafana (build into image later) -----
    EXTRA_ARGS: "-javaagent:/opt/jmx-exporter/jmx_prometheus_javaagent-0.19.0.jar=9404:/opt/jmx-exporter/kafka-3_0_0.yml"
    # TIERED STORAGE
    KAFKA_CFG_LOG4J_LOGGERS: "io.aiven.kafka.tieredstorage=DEBUG,org.apache.kafka.common.security=DEBUG,org.apache.kafka.server.log.remote.metadata.storage=DEBUG" # Increase Tiered Storage log level
    KAFKA_CFG_REMOTE_LOG_STORAGE_SYSTEM_ENABLE: "true" # Enable Tiered Storage
    KAFKA_CFG_LOG_RETENTION_CHECK_INTERVAL_MS: 300000 # (5 minutes) The frequency in milliseconds that the log cleaner checks whether any log is eligible for deletion
    KAFKA_CFG_REMOTE_LOG_MANAGER_TASK_INTERVAL_MS: 30000 # (30 seconds) Interval at which remote log manager runs the scheduled tasks like copy segments, and clean up remote log segments.
    # Remote metadata manager
    KAFKA_CFG_REMOTE_LOG_METADATA_MANAGER_CLASS_NAME: "org.apache.kafka.server.log.remote.metadata.storage.TopicBasedRemoteLogMetadataManager"
    KAFKA_CFG_REMOTE_LOG_METADATA_MANAGER_LISTENER_NAME: "BROKER"
    KAFKA_CFG_RLMM_CONFIG_REMOTE_LOG_METADATA_TOPIC_REPLICATION_FACTOR: 3
    # ----- Configure the remote storage manager -----
    KAFKA_CFG_REMOTE_LOG_STORAGE_MANAGER_CLASS_PATH: "/opt/bitnami/kafka/plugins/core-0.0.1-SNAPSHOT/*:/opt/bitnami/kafka/plugins/s3-0.0.1-SNAPSHOT/*" 
    KAFKA_CFG_REMOTE_LOG_STORAGE_MANAGER_CLASS_NAME: "io.aiven.kafka.tieredstorage.RemoteStorageManager"
    KAFKA_CFG_RSM_CONFIG_CHUNK_SIZE: 4194304 # 4 MiB is the current recommended chunk size - Segment files are chunked into smaller parts to allow for faster processing
    # ----- Configure the fetch chunk cache -----
    KAFKA_CFG_RSM_CONFIG_FETCH_CHUNK_CACHE_CLASS: "io.aiven.kafka.tieredstorage.fetch.cache.DiskChunkCache"
    KAFKA_CFG_RSM_CONFIG_FETCH_CHUNK_CACHE_PATH: "/opt/bitnami/kafka/tiered-storage-cache"
    KAFKA_CFG_RSM_CONFIG_FETCH_CHUNK_CACHE_SIZE: 34359738368 # 32 GiB, cache size
    KAFKA_CFG_RSM_CONFIG_FETCH_CHUNK_CACHE_PREFETCH_MAX_SIZE: 16777216 # 16 MiB, The amount of data that should be eagerly prefetched and cached
    KAFKA_CFG_RSM_CONFIG_FETCH_CHUNK_CACHE_RETENTION_MS: 600000 # (10 minutes) Cache retention time in ms, -1 represents infinite retention
    KAFKA_CFG_RSM_CONFIG_CUSTOM_METADATA_FIELDS_INCLUDE: "REMOTE_SIZE" # Custom Metadata to be stored along Remote Log Segment metadata on Remote Log Metadata Manager back-end
    KAFKA_CFG_RSM_CONFIG_UPLOAD_RATE_LIMIT_BYTES_PER_SECOND: 157286400 # upload rate limit: 150 MiB (100-200 MiB is the current recommended range for rate limiting)
    # ----- Configure Minio storage backend -----
    KAFKA_CFG_RSM_CONFIG_KEY_PREFIX: "tieredstorage-test/"
    KAFKA_CFG_RSM_CONFIG_STORAGE_BACKEND_CLASS: "io.aiven.kafka.tieredstorage.storage.s3.S3Storage"
    KAFKA_CFG_RSM_CONFIG_STORAGE_S3_ENDPOINT_URL: "http://minio:9000"
    KAFKA_CFG_RSM_CONFIG_STORAGE_S3_BUCKET_NAME: "tieredstorage"
    KAFKA_CFG_RSM_CONFIG_STORAGE_S3_REGION: "ap-southeast-3"
    KAFKA_CFG_RSM_CONFIG_STORAGE_S3_PATH_STYLE_ACCESS_ENABLED: "true"
    KAFKA_CFG_RSM_CONFIG_STORAGE_AWS_ACCESS_KEY_ID: "minioadmin"
    KAFKA_CFG_RSM_CONFIG_STORAGE_AWS_SECRET_ACCESS_KEY: "minioadmin"

services:
  controller-1:
    <<: *controller-common
    hostname: controller-1
    container_name: controller-1
    environment:
      <<: *controller-env
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_LISTENERS: "CONTROLLER://controller-1:29092"
    volumes:
      - kafka_1_data:/bitnami/kafka

  controller-2:
    <<: *controller-common
    hostname: controller-2
    container_name: controller-2
    environment:
      <<: *controller-env
      KAFKA_CFG_NODE_ID: 2
      KAFKA_CFG_LISTENERS: "CONTROLLER://controller-2:29093"
    volumes:
      - kafka_2_data:/bitnami/kafka

  controller-3:
    <<: *controller-common
    hostname: controller-3
    container_name: controller-3
    environment:
      <<: *controller-env
      KAFKA_CFG_NODE_ID: 3
      KAFKA_CFG_LISTENERS: CONTROLLER://controller-3:29094
    volumes:
      - kafka_3_data:/bitnami/kafka

  broker-1:
    <<: *broker-common
    hostname: broker-1
    container_name: broker-1
    depends_on:
      - controller-1
      - controller-2
      - controller-3
    ports:
      - "9093:9093"
    environment:
      <<: *broker-env
      # KAFKA CLUSTER CONFIG
      KAFKA_CFG_NODE_ID: 4
      KAFKA_KRAFT_CLUSTER_ID: "YFBtZwBcR6iE35DdIJAx6w"
      # LISTENERS
      KAFKA_CFG_LISTENERS: "BROKER://broker-1:9092,EXTERNAL://0.0.0.0:9093"
      KAFKA_CFG_ADVERTISED_LISTENERS: "BROKER://broker-1:9092,EXTERNAL://x.x.x.x:9093"
    volumes:
      - kafka_4_data:/bitnami/kafka
      - ./jmx-exporter:/opt/jmx-exporter

  broker-2:
    <<: *broker-common
    hostname: broker-2
    container_name: broker-2
    depends_on:
      - controller-1
      - controller-2
      - controller-3
    ports:
      - "9094:9094"
    environment:
      <<: *broker-env
      # KAFKA CLUSTER CONFIG
      KAFKA_CFG_NODE_ID: 5
      KAFKA_KRAFT_CLUSTER_ID: "YFBtZwBcR6iE35DdIJAx6w"
      # LISTENERS
      KAFKA_CFG_LISTENERS: "BROKER://broker-2:9092,EXTERNAL://0.0.0.0:9094"
      KAFKA_CFG_ADVERTISED_LISTENERS: "BROKER://broker-2:9092,EXTERNAL://x.x.x.x:9094"
    volumes:
      - kafka_5_data:/bitnami/kafka
      - ./jmx-exporter:/opt/jmx-exporter

  broker-3:
    <<: *broker-common
    hostname: broker-3
    container_name: broker-3
    depends_on:
      - controller-1
      - controller-2
      - controller-3
    ports:
      - "9095:9095"
    environment:
      <<: *broker-env
      # KAFKA CLUSTER CONFIG
      KAFKA_CFG_NODE_ID: 6
      KAFKA_KRAFT_CLUSTER_ID: "YFBtZwBcR6iE35DdIJAx6w"
      # LISTENERS
      KAFKA_CFG_LISTENERS: "BROKER://broker-3:9092,EXTERNAL://0.0.0.0:9095"
      KAFKA_CFG_ADVERTISED_LISTENERS: "BROKER://broker-3:9092,EXTERNAL://x.x.x.x:9095"
    volumes:
      - kafka_6_data:/bitnami/kafka
      - ./jmx-exporter:/opt/jmx-exporter

volumes:
  kafka_1_data:
    driver: local
  kafka_2_data:
    driver: local
  kafka_3_data:
    driver: local
  kafka_4_data:
    driver: local
  kafka_5_data:
    driver: local
  kafka_6_data:
    driver: local
```

My cluster also uses SASL_PLAINTEXT for authentication between the controller-broker and broker-client (the broker-broker authentication has been commented out).

Hope to hear from you soon.
